#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-celluloid
Version  : 0.17.3
Release  : 6
URL      : https://rubygems.org/downloads/celluloid-0.17.3.gem
Source0  : https://rubygems.org/downloads/celluloid-0.17.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-benchmark_suite
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-docile
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-guard-rspec
BuildRequires : rubygem-hitimes
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-netrc
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-rubocop
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-thor
BuildRequires : rubygem-timers
BuildRequires : rubygem-tins
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext

%description
![Celluloid](https://raw.github.com/celluloid/celluloid-logos/master/celluloid/celluloid.png)
=========
[![Gem Version](https://badge.fury.io/rb/celluloid.svg)](http://rubygems.org/gems/celluloid)
[![Build Status](https://secure.travis-ci.org/celluloid/celluloid.svg?branch=master)](http://travis-ci.org/celluloid/celluloid)
[![Code Climate](https://codeclimate.com/github/celluloid/celluloid.svg)](https://codeclimate.com/github/celluloid/celluloid)
[![Coverage Status](https://coveralls.io/repos/celluloid/celluloid/badge.svg?branch=master)](https://coveralls.io/r/celluloid/celluloid)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n celluloid-0.17.3
gem spec %{SOURCE0} -l --ruby > rubygem-celluloid.gemspec

%build
gem build rubygem-celluloid.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
celluloid-0.17.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/celluloid-0.17.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/README.md
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/CONDUCT.md
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/README.md
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/SYNC.md
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/celluloid-culture.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/gems/README.md
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/gems/dependencies.yml
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/gems/loader.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/rubocop/README.md
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/rubocop/lint.yml
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/rubocop/metrics.yml
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/rubocop/perf.yml
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/rubocop/rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/rubocop/style.yml
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/spec/gems_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/spec/sync_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/sync.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/tasks/rspec.rake
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/culture/tasks/rubocop.rake
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/examples/basic_usage.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/examples/futures.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/examples/ring.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/examples/simple_pmap.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/examples/stack.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/examples/timers.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/manager.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/autostart.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/backported.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/block.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/condition.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/core_ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/current.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/deprecate.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/fiber.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/pool.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/logging.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox/evented.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/managed.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/notices.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxies.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/abstract.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/actor.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/async.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/block.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/future.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/system_events.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/threaded.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/thread.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/actor/system_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/actor_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/block_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/calls_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/condition_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/evented_mailbox_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/future_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/group/elastic_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/group/pool_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/group/spawner_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/mailbox/evented_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/mailbox_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/misc/leak_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/task/fibered_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/task/threaded_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/celluloid/timer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/deprecate/actor_system_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/deprecate/block_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/deprecate/calls_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/deprecate/evented_mailbox_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/deprecate/future_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/deprecate/internal_pool_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/shared/actor_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/shared/group_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/shared/mailbox_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/shared/task_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/configure_rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/coverage.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/crash_checking.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/debugging.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/env.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/examples/actor_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/examples/call_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/examples/evented_mailbox_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/includer.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/logging.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/loose_threads.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/reset_class_variables.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/sleep_and_wait.rb
/usr/lib64/ruby/gems/2.3.0/gems/celluloid-0.17.3/spec/support/stubbing.rb
/usr/lib64/ruby/gems/2.3.0/specifications/celluloid-0.17.3.gemspec
